on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - develop
      - "release-*"
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches:
      - "main"

env:
  GOPRIVATE: "xiaoshiai.cn/*"
  GIT_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Build binaries
        run: make build

      # Release Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ${{ vars.REGISTRY }}
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: make login

      - name: Release Docker
        if: github.event_name != 'pull_request'
        run: make release-image

      - name: Release Helm Chart
        if: github.ref_type == 'tag'
        run: make release-helm
